version: '3.7'
services:
  app:
    build: ./docker
    container_name: app
    networks:
      - isucon-network
    ports:
      - "8080:443"
    volumes:
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
      - ./docker/conf/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./docker/conf/privkey.pem:/etc/nginx/ssl/privkey.pem
      - ./frontend:/home/isucon/isucari/webapp/frontend
      - ./php:/home/isucon/isucari/webapp/php
      - ./public:/home/isucon/isucari/webapp/public
      - ./sql:/home/isucon/isucari/webapp/sql
  db:
    image: percona:8
    container_name: db
    # Workaround: PHP don't support authentication method caching_sha2_password
    # https://github.com/docker-library/mysql/issues/454
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      - ./sql/00_create_database.sql:/docker-entrypoint-initdb.d/00-isucon.sql
    networks:
      - isucon-network
    environment:
      - MYSQL_ROOT_PASSWORD=248
      - MYSQL_USER=isucari
      - MYSQL_PASSWORD=isucari
      - MYSQL_DATABASE=isucari
networks:
  isucon-network:
    name: isucon-network
    ipam:
      config:
        - subnet: 192.168.248.0/24
