version: '3.7'
services:
  app:
    build: ./docker
    container_name: app
    networks:
      - isucon-network
    ports:
      - "8080:80"
    volumes:
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
      # - .:/opt/isucon/webapp/php
      # - ./static:/opt/isucon/webapp/static
  db:
    image: percona:5.7
    container_name: db
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      # - ./db/isucon.sql:/docker-entrypoint-initdb.d/00-isucon.sql
    networks:
      - isucon-network
    environment:
      - MYSQL_ROOT_PASSWORD=248
      - MYSQL_USER=isucon
      - MYSQL_PASSWORD=isucon
      - MYSQL_DATABASE=<REPLACE_ME>
networks:
  isucon-network:
    name: isucon-network
    ipam:
      config:
        - subnet: 192.168.248.0/24
